export interface VaultKeyMetadata {
  key: string;
  description?: string;
  isSet: boolean;
  maskedHint?: string;
  updatedAt?: number;
}

export class CredentialVault {
  private static instance: CredentialVault;
  private secrets: Map<string, string> = new Map();
  private metadata: Map<string, { description?: string; updatedAt: number }> = new Map();

  public static getInstance(): CredentialVault {
    if (!CredentialVault.instance) {
      CredentialVault.instance = new CredentialVault();
    }
    return CredentialVault.instance;
  }

  /**
   * Securely sets a secret in local memory.
   */
  public setSecret(key: string, value: string, description?: string): void {
    const cleanKey = key.trim().toUpperCase().replace(/[^A-Z0-9_]/g, "_");
    if (!cleanKey) throw new Error("Invalid secret key name");
    this.secrets.set(cleanKey, value);
    this.metadata.set(cleanKey, {
      description,
      updatedAt: Date.now(),
    });
  }

  /**
   * Check if a secret exists.
   */
  public hasSecret(key: string): boolean {
    const cleanKey = key.trim().toUpperCase().replace(/[^A-Z0-9_]/g, "_");
    return this.secrets.has(cleanKey) && (this.secrets.get(cleanKey)?.length || 0) > 0;
  }

  /**
   * Internal retrieval for runtime execution only.
   * NEVER exposed to the AI agent via MCP tools or chat.
   */
  public getSecretValue(key: string): string | undefined {
    const cleanKey = key.trim().toUpperCase().replace(/[^A-Z0-9_]/g, "_");
    return this.secrets.get(cleanKey);
  }

  /**
   * Returns list of keys with presence status and descriptions.
   * Values are strictly omitted to guarantee zero-knowledge exposure to AI agents.
   */
  public listKeys(): VaultKeyMetadata[] {
    const result: VaultKeyMetadata[] = [];
    for (const [key, val] of this.secrets.entries()) {
      const meta = this.metadata.get(key);
      const hint = val.length > 6 ? `${val.substring(0, 3)}...${val.slice(-2)}` : "***";
      result.push({
        key,
        isSet: val.length > 0,
        description: meta?.description,
        maskedHint: hint,
        updatedAt: meta?.updatedAt,
      });
    }
    return result;
  }

  /**
   * Removes a secret.
   */
  public deleteSecret(key: string): boolean {
    const cleanKey = key.trim().toUpperCase().replace(/[^A-Z0-9_]/g, "_");
    this.metadata.delete(cleanKey);
    return this.secrets.delete(cleanKey);
  }

  /**
   * Replaces $vault:KEY or {{vault.KEY}} or {{secrets.KEY}} references with actual values at execution time.
   */
  public resolveSecrets(input: any): any {
    if (typeof input === "string") {
      return input.replace(
        /(?:\$vault:|{{(?:vault|secrets)\.)([A-Za-z0-9_]+)(?:}})?/g,
        (_match, keyName) => {
          const secret = this.getSecretValue(keyName);
          return secret !== undefined ? secret : `[UNRESOLVED_SECRET:${keyName}]`;
        }
      );
    }

    if (Array.isArray(input)) {
      return input.map((item) => this.resolveSecrets(item));
    }

    if (input && typeof input === "object") {
      const copy: Record<string, any> = {};
      for (const [k, v] of Object.entries(input)) {
        copy[k] = this.resolveSecrets(v);
      }
      return copy;
    }

    return input;
  }

  /**
   * Redacts secret values from log payloads so they never leak into logs or agent outputs.
   */
  public redactSecrets(input: any): any {
    if (typeof input === "string") {
      let sanitized = input;
      for (const [key, val] of this.secrets.entries()) {
        if (val && val.length > 3) {
          sanitized = sanitized.split(val).join(`[REDACTED:$vault:${key}]`);
        }
      }
      return sanitized;
    }

    if (Array.isArray(input)) {
      return input.map((item) => this.redactSecrets(item));
    }

    if (input && typeof input === "object") {
      const copy: Record<string, any> = {};
      for (const [k, v] of Object.entries(input)) {
        copy[k] = this.redactSecrets(v);
      }
      return copy;
    }

    return input;
  }

  /**
   * Generates a standard .env file for local download.
   */
  public exportDotEnv(): string {
    let lines = "# Local Environment Secrets Vault\n# Generated by KDD Flow Engine (Client-side only)\n\n";
    for (const [key, val] of this.secrets.entries()) {
      const meta = this.metadata.get(key);
      if (meta?.description) {
        lines += `# ${meta.description}\n`;
      }
      lines += `${key}=${val}\n`;
    }
    return lines;
  }
}
